### ISSUE TITLE
Design Suggestions

### ISSUE THREAD

**Issue by nikolasburk** [howtographql/howtographql#21]
- [ ] instruction blocks in the content should be visually marked so that readers can potentially skip content and only follow the instructions if they want to get through quicker
- [ ] code blocks should have a way to be annotated, e.g. with the file name where that code is located
-  [ ] there should be two kinds of code blocks, one that communicates that the user needs to paste the contents in their own code, the other one communicates that this is example code that the user doesn't have to take any action on
