### ISSUE TITLE
Website Implementation

### ISSUE THREAD

**Issue by timsuchanek** [howtographql/howtographql#36]
# Todo General

 - [x] content overview landingpage (1h)
 - [x] author bio view, author bio data, author frontmatter (1h)
- [x] video author view (0.5h)
- [x] final success screen (2h)
 - [x] add bonus chapter screen (0.5h)
 - [x] localstorage tracking + score calculation (1h)
 - [x] reflect seen chapters to steps (0.5h)
 - [x] implement question data structure + handling of wrong questions (0.5h)
   - [x] hide question when answered correctly
   - [x] show correct next chapter count `n`
   - [x] also reset answers
 - [x] minor sidebar css issues (in sum 1h)
   - [x] bullets background color (10min)
   - [x] last point without line (15min)
   - [x] GRAPHQL THEORY same alignment as points (5min)
 - [x] nav dropdowns (1.5h)
- [x] search (1.5h)
 SUM: 11h

## added later
 - [x] fix [object Object] problem in prerendered versino
 - [x] implement stack switch
 - [x] increase animation time based on path length
 - [x] stop answers from jumping
 - [x] hide skip when answered
 - [x] vertical alignment questions
 - [x] menu dropdown - real links
 - [x] menu dropdown - close on click
 - [x] search - real results
 - [x] explore caption for image solutions
 - [x] video play icon
 - [x] remove header easter eggs

# Mobile
## Todo Mobile
 - [x] landingpage (4h)
 - [x] markdown (1h)
 - [x] questions (0.5h)

## Needed Design Solutions Julian
 - [x] done chapter in Chooser on Landinpage
 - [x] Chapter overview - overflow, same for sidebar
 - [x] success screen mobile

## Needed SVGs
 - [x] logos for different technologies
 - [x] header hamburger svg
 - [x] next chapter + bonus icons
 - [x] play symbol video preview
 - [x] medal for success screen

## Mobile Responsiveness Julian
 - [x] Intro
 - [x] Chooser
 - [x] Header (just nav), Tim will do dropdown later
 - [x] Learn by Building Section
 - [x] Community Section
 - [x] Content Overview Section

## Questions
 - Watch Overview: Video modal?

## Fine Tuning
 - [x] Relay Logo too big
 - [x] more lineheight for content overview
 - [x] line height of copy

## Feedback @schickling

- [x] Track selection: Backend tracks should include the language logo (nodejs + graphql logo, python + graphene logo, ...)
- [x] Fav icon is missing 
- [x] Remove Lee Byron + Facebook for now
- [x] Add Sashko + Apollo logo
- [x] Hover states
- [x] Adjust headline sizes to match Graphcool docs
- [x] Reflect site title in `<title>`
- [x] Use same logo order as in design for tutorial selection (react/apollo in the center)
- [x] Add beginner's choice
- [x] Success section should have coloured confetti 🎉 
- [x] Test section: The skip button should be hidden when answered correctly
- [x] Frontpage: Video icon + duration should be clickable and directly trigger autoplay on the chapter page
- [ ] Replace hackernews picture with video (use ffmpeg to compress - see graphql-up/freecom for example)
- [x] Content folder needs to be on root level: `/content`
- [x] Make Graphcool link in footer a subtle link
- [x] Add rounded arrow to playground section on frontpage
- [x] Make community section rather wide than high
- [x] Top nav github button should be `target=_blank`
- [x] "Edit this page on Github" button
- [x] Add preview banner
- [x] Remove docs label on frontpage playground
- [ ] Page flickers on first load
- [x] Content doesn't scroll smoothly on mobile
- [x] frontpage playground: Query is malformated

## Feedback @nikolasburk

- [x] Add "Coming Soon"-label in chooser

**Comment by timsuchanek** [comment]
Let's continue in https://github.com/howtographql/howtographql/issues/42
